language: python
python:
  - "2.7"

install:
  - pip install -r dependencies.txt

script:
  - echo "Testing Finder"
  - python Finder/finder-test.py


notifications:
    email:
        recipients:
            - mateusgabimoreira@gmail.com